
// 请求错误
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const MENUCOLLAPSED = 'MENUCOLLAPSED'; // 左边菜单是否展开
export const GETFUNCMENUSUCCESS = 'GETFUNCMENUSUCCESS'; // 左边菜单
export const ACTIVEMENU = 'ACTIVEMENU'; // 当前选种菜单
export const CONFIGSUCCESS = 'CONFIGSUCCESS'; // 当前选种菜单
// ========== admin
export const LOGINSUCCESS = 'LOGINSUCCESS';

// ========== articles 文章管理
export const ARTICLEADDSUCCESS = 'ARTICLEADDSUCCESS'; // 新增
export const ARTICLELISTSUCCESS = 'ARTICLELISTSUCCESS'; // 查询
export const ARTICLEDELSUCCESS = 'ARTICLEDELSUCCESS'; // 删除
export const ARTICLEUPDATESUCCESS = 'ARTICLEUPDATESUCCESS'; // 更新

// ========== project 项目管理
export const PROJECTADDSUCCESS = 'PROJECTADDSUCCESS'; // 新增
export const PROJECTLISTSUCCESS = 'PROJECTLISTSUCCESS'; // 查询
export const PROJECTDELSUCCESS = 'PROJECTDELSUCCESS'; // 删除
export const PROJECTUPDATESUCCESS = 'PROJECTUPDATESUCCESS'; // 更新
export const UPDATEPROSTATUS = 'UPDATEPROSTATUS'; // 更新
export const PROJECTDETAILSUCCESS = 'PROJECTDETAILSUCCESS'; // 详情
